---
apiVersion: v1
kind: Service
metadata:
  name: becpg-transform-markdown
  labels:
    app: becpg-transform-markdown
    part-of: transformers
    app.kubernetes.io/name: becpg-transform-markdown
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: transformer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: becpg-ci
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: becpg-transform-markdown
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: becpg-transform-markdown
  labels:
    app: becpg-transform-markdown
    part-of: transformers
    app.kubernetes.io/name: becpg-transform-markdown
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: transformer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: becpg-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: becpg-transform-markdown
  template:
    metadata:
      labels:
        app: becpg-transform-markdown
        part-of: transformers
        app.kubernetes.io/name: becpg-transform-markdown
        app.kubernetes.io/instance: dev
        app.kubernetes.io/component: transformer
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: becpg-ci
    spec:
      containers:
        - name: becpg-transform-markdown
          image: europe-west1-docker.pkg.dev/becpg-314807/becpg-docker/becpg-transform-markdown:latest        
          securityContext:
            runAsNonRoot: true
            runAsUser: 33002
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8090
          env:
            - name: JAVA_OPTS
              value: " -Xms256m -Xmx256m"
          resources:
            requests:
              memory: "4000Mi"
            limits:
              memory: "4500Mi"
          startupProbe:
            httpGet:
              path: /live
              port: 8090
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
