server.port=8090
transform.core.markitdown.script.path=/usr/local/bin/markitdown-convert.sh
transform.core.markitdown.timeout.ms=900000
transform.core.md2pdf.script.path=/usr/local/bin/md2pdf-convert.sh
transform.core.md2pdf.timeout.ms=300000
transform.core.pymupdf4llm.script.path=/usr/local/bin/pymupdf4llm-convert.sh
transform.core.pymupdf4llm.timeout.ms=900000
