services:
  becpg-transform-markdown:
    image: ${docker.becpg.url}/becpg-transform-markdown:${docker.becpg.tag}
    build:
      tags:
       - ${docker.becpg.url}/becpg-transform-markdown:${docker.becpg.tag}
       - ${docker.becpg.url}/becpg-transform-markdown:${docker.becpg.version}
      dockerfile: ./Dockerfile
      context: ${project.basedir}/target/   
    restart: unless-stopped
    ports:
      - 8090:8090
